package com.biit.drools 

import java.lang.Math 
import java.util.Date 
import java.util.List 
import java.util.ArrayList 
import com.biit.form.submitted.* 
import com.biit.drools.form.* 
import com.biit.orbeon.form.* 
import com.biit.drools.utils.* 
import com.biit.drools.plugins.PluginController 
import net.xeoh.plugins.base.Plugin 
import com.biit.plugins.interfaces.IPlugin 
import java.lang.reflect.Method 
import com.biit.drools.logger.DroolsEngineLogger 

declare FiredRule
	ruleName : String
end

//******************************************************************************
//*                              GLOBAL VARIABLES                              *
//******************************************************************************
global java.lang.Number IVA
global java.lang.String TestPC
global java.util.Date TestDate

//******************************************************************************
//*                           DEFAULT VALUE VARIABLES                          *
//******************************************************************************
//******************************************************************************
//*                                FORM RULES                                  *
//******************************************************************************
rule "helloWorldExpression_6dfbf678b1f04f55927b8d82257d26c7"
when
	$droolsForm: DroolsForm()
	$formform : DroolsSubmittedForm() from $droolsForm.getDroolsSubmittedForm() 
then
	Object callResult = PluginController.getInstance().executePluginMethod('com.biit.plugins.interfaces.IPlugin', 'DroolsFunctions', 'methodSumParameters', 4.0, 4.0);
	$formform.setVariableValue('customVariableResult', callResult);
	DroolsEngineLogger.debug("DroolsRule", "Variable set (form, customVariableResult, callResult)");
end

